// This file will be auto-generated by `supabase gen types typescript`
// Placeholder until Supabase project is connected

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: string
          first_name: string
          last_name: string
          email: string
          phone: string | null
          avatar_url: string | null
          organization_id: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role: string
          first_name: string
          last_name: string
          email: string
          phone?: string | null
          avatar_url?: string | null
          organization_id: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: string
          first_name?: string
          last_name?: string
          email?: string
          phone?: string | null
          avatar_url?: string | null
          organization_id?: string
          is_active?: boolean
          updated_at?: string
        }
      }
      participants: {
        Row: {
          id: string
          profile_id: string | null
          ndis_number: string
          first_name: string
          last_name: string
          date_of_birth: string | null
          phone: string | null
          email: string | null
          address_line_1: string | null
          address_line_2: string | null
          suburb: string | null
          state: string
          postcode: string | null
          latitude: number | null
          longitude: number | null
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          notes: string | null
          organization_id: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['participants']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }
        Update: Partial<Database['public']['Tables']['participants']['Row']>
      }
      workers: {
        Row: {
          id: string
          profile_id: string
          employee_id: string | null
          qualification: string[]
          services_provided: string[]
          hourly_rate: number | null
          max_hours_per_week: number
          organization_id: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['workers']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }
        Update: Partial<Database['public']['Tables']['workers']['Row']>
      }
      shifts: {
        Row: {
          id: string
          participant_id: string
          worker_id: string
          service_agreement_item_id: string | null
          scheduled_start: string
          scheduled_end: string
          actual_start: string | null
          actual_end: string | null
          status: string
          check_in_latitude: number | null
          check_in_longitude: number | null
          check_out_latitude: number | null
          check_out_longitude: number | null
          cancellation_reason: string | null
          notes: string | null
          organization_id: string
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['shifts']['Row'], 'id' | 'created_at' | 'updated_at' | 'status'> & { id?: string; status?: string; created_at?: string; updated_at?: string }
        Update: Partial<Database['public']['Tables']['shifts']['Row']>
      }
      invoices: {
        Row: {
          id: string
          invoice_number: string
          participant_id: string
          plan_id: string | null
          invoice_date: string
          due_date: string | null
          subtotal: number
          gst: number
          total: number
          status: string
          payment_reference: string | null
          notes: string | null
          organization_id: string
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['invoices']['Row'], 'id' | 'created_at' | 'updated_at' | 'invoice_number'> & { id?: string; invoice_number?: string; created_at?: string; updated_at?: string }
        Update: Partial<Database['public']['Tables']['invoices']['Row']>
      }
      case_notes: {
        Row: {
          id: string
          shift_id: string | null
          participant_id: string
          worker_id: string
          note_date: string
          content: string
          goals_addressed: string[]
          participant_response: string | null
          follow_up_required: boolean
          follow_up_notes: string | null
          is_draft: boolean
          attachments: string[]
          organization_id: string
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['case_notes']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }
        Update: Partial<Database['public']['Tables']['case_notes']['Row']>
      }
    }
    Functions: {
      get_user_role: {
        Args: Record<string, never>
        Returns: string
      }
      is_admin_or_coordinator: {
        Args: Record<string, never>
        Returns: boolean
      }
      get_user_organization_id: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Views: {
      [_ in never]: never
    }
    Enums: {
      app_role: 'admin' | 'coordinator' | 'worker' | 'participant'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
