// This file will be auto-generated by `supabase gen types typescript`
// Placeholder until Supabase project is connected

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: string
          first_name: string
          last_name: string
          email: string
          phone: string | null
          avatar_url: string | null
          organization_id: string
          is_active: boolean
          is_platform_admin: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role: string
          first_name: string
          last_name: string
          email: string
          phone?: string | null
          avatar_url?: string | null
          organization_id: string
          is_active?: boolean
          is_platform_admin?: boolean | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: string
          first_name?: string
          last_name?: string
          email?: string
          phone?: string | null
          avatar_url?: string | null
          organization_id?: string
          is_active?: boolean
          is_platform_admin?: boolean | null
          updated_at?: string
        }
        Relationships: []
      }
      organizations: {
        Row: {
          id: string
          name: string
          abn: string | null
          settings: Json | null
          xero_token_set: Json | null
          xero_tenant_id: string | null
          xero_contact_mapping: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          abn?: string | null
          settings?: Json | null
          xero_token_set?: Json | null
          xero_tenant_id?: string | null
          xero_contact_mapping?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          abn?: string | null
          settings?: Json | null
          xero_token_set?: Json | null
          xero_tenant_id?: string | null
          xero_contact_mapping?: Json | null
          updated_at?: string
        }
        Relationships: []
      }
      participants: {
        Row: {
          id: string
          profile_id: string | null
          ndis_number: string
          first_name: string
          last_name: string
          date_of_birth: string | null
          phone: string | null
          email: string | null
          address_line_1: string | null
          address_line_2: string | null
          suburb: string | null
          state: string
          postcode: string | null
          latitude: number | null
          longitude: number | null
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          notes: string | null
          organization_id: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id?: string | null
          ndis_number: string
          first_name: string
          last_name: string
          date_of_birth?: string | null
          phone?: string | null
          email?: string | null
          address_line_1?: string | null
          address_line_2?: string | null
          suburb?: string | null
          state?: string
          postcode?: string | null
          latitude?: number | null
          longitude?: number | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          notes?: string | null
          organization_id: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          profile_id?: string | null
          ndis_number?: string
          first_name?: string
          last_name?: string
          date_of_birth?: string | null
          phone?: string | null
          email?: string | null
          address_line_1?: string | null
          address_line_2?: string | null
          suburb?: string | null
          state?: string
          postcode?: string | null
          latitude?: number | null
          longitude?: number | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          notes?: string | null
          organization_id?: string
          is_active?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'participants_organization_id_fkey'
            columns: ['organization_id']
            isOneToOne: false
            referencedRelation: 'organizations'
            referencedColumns: ['id']
          },
        ]
      }
      workers: {
        Row: {
          id: string
          profile_id: string
          employee_id: string | null
          qualification: string[]
          services_provided: string[]
          hourly_rate: number | null
          max_hours_per_week: number
          organization_id: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          employee_id?: string | null
          qualification?: string[]
          services_provided?: string[]
          hourly_rate?: number | null
          max_hours_per_week?: number
          organization_id: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          profile_id?: string
          employee_id?: string | null
          qualification?: string[]
          services_provided?: string[]
          hourly_rate?: number | null
          max_hours_per_week?: number
          organization_id?: string
          is_active?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      shifts: {
        Row: {
          id: string
          participant_id: string
          worker_id: string
          service_agreement_item_id: string | null
          scheduled_start: string
          scheduled_end: string
          actual_start: string | null
          actual_end: string | null
          status: string
          check_in_latitude: number | null
          check_in_longitude: number | null
          check_out_latitude: number | null
          check_out_longitude: number | null
          cancellation_reason: string | null
          notes: string | null
          organization_id: string
          created_by: string | null
          reminder_24h_sent: boolean | null
          reminder_2h_sent: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          participant_id: string
          worker_id: string
          service_agreement_item_id?: string | null
          scheduled_start: string
          scheduled_end: string
          actual_start?: string | null
          actual_end?: string | null
          status?: string
          check_in_latitude?: number | null
          check_in_longitude?: number | null
          check_out_latitude?: number | null
          check_out_longitude?: number | null
          cancellation_reason?: string | null
          notes?: string | null
          organization_id: string
          created_by?: string | null
          reminder_24h_sent?: boolean | null
          reminder_2h_sent?: boolean | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          participant_id?: string
          worker_id?: string
          service_agreement_item_id?: string | null
          scheduled_start?: string
          scheduled_end?: string
          actual_start?: string | null
          actual_end?: string | null
          status?: string
          check_in_latitude?: number | null
          check_in_longitude?: number | null
          check_out_latitude?: number | null
          check_out_longitude?: number | null
          cancellation_reason?: string | null
          notes?: string | null
          organization_id?: string
          created_by?: string | null
          reminder_24h_sent?: boolean | null
          reminder_2h_sent?: boolean | null
          updated_at?: string
        }
        Relationships: []
      }
      invoices: {
        Row: {
          id: string
          invoice_number: string
          participant_id: string
          plan_id: string | null
          invoice_date: string
          due_date: string | null
          subtotal: number
          gst: number
          total: number
          status: string
          payment_reference: string | null
          notes: string | null
          organization_id: string
          created_by: string | null
          xero_invoice_id: string | null
          xero_sync_status: 'pending' | 'synced' | 'failed' | 'not_applicable' | null
          xero_sync_error: string | null
          xero_synced_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          invoice_number?: string
          participant_id: string
          plan_id?: string | null
          invoice_date: string
          due_date?: string | null
          subtotal: number
          gst?: number
          total: number
          status?: string
          payment_reference?: string | null
          notes?: string | null
          organization_id: string
          created_by?: string | null
          xero_invoice_id?: string | null
          xero_sync_status?: 'pending' | 'synced' | 'failed' | 'not_applicable' | null
          xero_sync_error?: string | null
          xero_synced_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          invoice_number?: string
          participant_id?: string
          plan_id?: string | null
          invoice_date?: string
          due_date?: string | null
          subtotal?: number
          gst?: number
          total?: number
          status?: string
          payment_reference?: string | null
          notes?: string | null
          organization_id?: string
          created_by?: string | null
          xero_invoice_id?: string | null
          xero_sync_status?: 'pending' | 'synced' | 'failed' | 'not_applicable' | null
          xero_sync_error?: string | null
          xero_synced_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      ndis_plans: {
        Row: {
          id: string
          participant_id: string
          plan_number: string | null
          start_date: string
          end_date: string
          total_budget: number
          used_budget: number
          status: string
          organization_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          participant_id: string
          plan_number?: string | null
          start_date: string
          end_date: string
          total_budget: number
          used_budget?: number
          status?: string
          organization_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          participant_id?: string
          plan_number?: string | null
          start_date?: string
          end_date?: string
          total_budget?: number
          used_budget?: number
          status?: string
          organization_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'ndis_plans_participant_id_fkey'
            columns: ['participant_id']
            isOneToOne: false
            referencedRelation: 'participants'
            referencedColumns: ['id']
          },
        ]
      }
      case_notes: {
        Row: {
          id: string
          shift_id: string | null
          participant_id: string
          worker_id: string
          note_date: string
          content: string
          goals_addressed: string[]
          participant_response: string | null
          follow_up_required: boolean
          follow_up_notes: string | null
          is_draft: boolean
          attachments: string[]
          organization_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          shift_id?: string | null
          participant_id: string
          worker_id: string
          note_date: string
          content: string
          goals_addressed?: string[]
          participant_response?: string | null
          follow_up_required?: boolean
          follow_up_notes?: string | null
          is_draft?: boolean
          attachments?: string[]
          organization_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          shift_id?: string | null
          participant_id?: string
          worker_id?: string
          note_date?: string
          content?: string
          goals_addressed?: string[]
          participant_response?: string | null
          follow_up_required?: boolean
          follow_up_notes?: string | null
          is_draft?: boolean
          attachments?: string[]
          organization_id?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Functions: {
      get_user_role: {
        Args: Record<string, never>
        Returns: string
      }
      is_admin_or_coordinator: {
        Args: Record<string, never>
        Returns: boolean
      }
      get_user_organization_id: {
        Args: Record<string, never>
        Returns: string
      }
      is_platform_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
    }
    Views: {
      [_ in never]: never
    }
    Enums: {
      app_role: 'admin' | 'coordinator' | 'worker' | 'participant'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
